services:
  db:
    build: .docker/postgres
    container_name: collec-backend-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/dbdata
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=collec-backend
